"""Add user role

Revision ID: 42e85865af7d
Revises: 818d1c6930c4
Create Date: 2022-02-20 16:13:44.070960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '42e85865af7d'
down_revision = '818d1c6930c4'
branch_labels = None
depends_on = None


def upgrade():
    user_role = postgresql.ENUM('super admin', 'admin', 'user', name='userrole')
    user_role.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrole'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
